### ISSUE TITLE
Minimum supported Servlet version?

### ISSUE THREAD

**Issue by martin-g** [Atmosphere/atmosphere#2003] opened 2015-06-24 08:16 UTC
Hi,

I'm trying to upgrade Atmosphere in Wicket-Atmosphere from 2.2.2 to something newer.
First I tried to 2.2.7 (last 2.2.x) but it fails when using the app with Chrome with:
```
java.lang.NoSuchMethodError: javax.servlet.http.HttpServletResponse.getHeader(Ljava/lang/String;)Ljava/lang/String;
	at org.atmosphere.cpr.AtmosphereResponse.getHeader(AtmosphereResponse.java:414)
	at org.atmosphere.interceptor.CorsInterceptor.inspect(CorsInterceptor.java:57)
	at org.atmosphere.cpr.AsynchronousProcessor.invokeInterceptors(AsynchronousProcessor.java:312)
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:169)
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:107)
	at org.atmosphere.container.Jetty7CometSupport.service(Jetty7CometSupport.java:57)
	at org.atmosphere.container.JettyAsyncSupportWithWebSocket.service(JettyAsyncSupportWithWebSocket.java:67)
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2078)
	at org.atmosphere.cpr.AtmosphereServlet.doPost(AtmosphereServlet.java:198)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:652)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1317)
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:267)
....
````

2.2.2-2.2.6 has no this problem.
http://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletResponse.html#getHeader(java.lang.String) is `@since 3.0`. 
The application runs on Jetty 7.6.15 with Servlet 2.5. Is this still supported?
What is the mininum

**Comment by martin-g** [comment] 2015-06-24 08:16
https://issues.apache.org/jira/browse/WICKET-5930

**Comment by jfarcand** [comment] 2015-06-24 12:04
Duplicate of #1987

**Closed by jfarcand** 2015-06-24 12:04 UTC
