### ISSUE TITLE
[Meteor][Jersey][JSONP] doPost is executed before doGet when data is pushed from subSocket.onOpen()

### ISSUE THREAD

**Issue by slovdahl** [Atmosphere/atmosphere#1832] opened 2015-01-07 13:34 UTC
Tested with latest 2.3.0-SNAPSHOT and modified meteor-chat sample:

```diff
diff --git a/samples/meteor-chat/src/main/java/org/atmosphere/samples/chat/MeteorChat.java b/samples/meteor-chat/src/main/java/org/atmosphere/samples/chat/MeteorChat.java
index 64e50c0..45d1189 100755
--- a/samples/meteor-chat/src/main/java/org/atmosphere/samples/chat/MeteorChat.java
+++ b/samples/meteor-chat/src/main/java/org/atmosphere/samples/chat/MeteorChat.java
@@ -48,6 +48,7 @@ public class MeteorChat extends HttpServlet {
      */
     @Override
     public void doGet(HttpServletRequest req, HttpServletResponse res) throws IOException {
+        System.out.println(System.currentTimeMillis() + ": DOGET");
         // Set the logger level to TRACE to see what's happening.
         Meteor.build(req).addListener(new AtmosphereResourceEventListenerAdapter());
     }
@@ -60,6 +61,7 @@ public class MeteorChat extends HttpServlet {
      */
     @Override
     public void doPost(HttpServletRequest req, HttpServletResponse res) throws IOException {
+        System.out.println(System.currentTimeMillis() + ": DOPOST");
         String body = req.getReader().readLine().trim();
         // Simple JSON -- Use Jackson for more complex structure
         // Message looks like { "author" : "foo", "message" : "bar" }
diff --git a/samples/meteor-chat/src/main/webapp/jquery/application.js b/samples/meteor-chat/src/main/webapp/jquery/application.js
index 8657f8a..e72fc28 100644
--- a/samples/meteor-chat/src/main/webapp/jquery/application.js
+++ b/samples/meteor-chat/src/main/webapp/jquery/application.js
@@ -11,7 +11,7 @@ $(function () {
     var request = { url: document.location.toString() + 'meteor',
                     contentType : "application/json",
                     logLevel : 'debug',
-                    transport : 'websocket' ,
+                    transport : 'jsonp',
 reconnectInterval : 5000,
                     fallbackTransport: 'long-polling'};
 
@@ -20,6 +20,8 @@ reconnectInterval : 5000,
         content.html($('<p>', { text: 'Atmosphere connected using ' + response.transport }));
         input.removeAttr('disabled').focus();
         status.text('Choose name:');
+        var first = "author" + new Date().getMilliseconds();
+        subSocket.push(jQuery.stringifyJSON({ author: first, message: first }));
     };
```

Deploy the sample in jetty, open http://localhost:8080 in the web browser and check in the log output and notice the following:
```
1420636686961: DOPOST
1420636686964: DOGET
```

So, if a subSocket.push("...") is done in request.onOpen(), the doPost() method is executed before doGet() in MeteorChat.

**Comment by jfarcand** [comment] 2015-01-07 16:25
Workaround is to add a `sleep` inside the `onOpen`. I don't think this issue can be fixed, unfrotunately. Also, the issue should be moved to https://github.com/Atmosphere/atmosphere-javascript :-)

**Comment by slovdahl** [comment] 2015-01-08 06:42
It's also a problem with jersey (maybe quite obvious). However, I was sure it worked well previously, and I was right :) With 2.0.7 it works fine at least, haven't tested any other 2.0.x versions.

**Comment by jfarcand** [comment] 2015-01-08 13:24
@slovdahl The problem is with the javascript for sure.

**Comment by slovdahl** [comment] 2015-01-08 13:48
Okay, but the same javascript works with 2.0.7, but not with 2.1.4, 2.1.6, 2.1.9 and 2.2.4.

**Comment by jfarcand** [comment] 2015-01-08 13:50
I think it is just a timing issue and if you test many times, the issue will arise IMO. You are using the latest `atmosphere.js` for testing, right?

**Comment by slovdahl** [comment] 2015-01-08 13:58
With the sample yes, but not with my own application.

Tried opening http://localhost:8080 running the sample 20 times, and every single time doPost was executed before doGet.

**Comment by jfarcand** [comment] 2015-01-23 15:49
Closing as won't fix because a simple workaround is to add
```js
       setTimeout(function (){
           socket.push(request);
        }, 100);
```
Another solution would consist of writing an `AtmosphereInterceptor` and delay the delivery of the `POST` until the `GET` is received. But it will require synchronization and I'm not sure it will perform well.

**Closed by jfarcand** 2015-01-23 15:49 UTC
Labels: Documentation, Workaround Available
