### ISSUE TITLE
[jsr356] Spring mvc and atmosphere : works with tomcat7, not with tomcat 8

### ISSUE THREAD

**Issue by 4th-line** [Atmosphere/atmosphere#2050] opened 2015-09-15 19:07 UTC
See https://groups.google.com/forum/#!topic/atmosphere-framework/_HcSt72BFW4

Test case (chat application) : http://bit.ly/1QfDnzV 
libs : atmosphere 2.3.1, spring mvc 4.2
maven goals : 
* package to create a war that can be deployed on tomcat 7 or tomcat 8
* tomcat7:run to deploy on tomcat with the maven tomcat 7 plugin

**Comment by jfarcand** [comment] 2015-09-16 00:25
@4th-line Do me a favor and integrate your sample within https://github.com/Atmosphere/atmosphere-samples by doing a pull request. I will for sure get rid of the old stuff :-) Will look ASAP at the issue.Thanks!

**Comment by popkutty** [comment] 2015-09-16 09:00
I'm also facing the same issue. Any trouble shooting for this?

**Comment by jfarcand** [comment] 2015-09-16 12:51
@popkutty Your contribution welcomed :-)

**Comment by 4th-line** [comment] 2015-09-16 18:13
@jfarcand Hi, I added a pull request (named initial commit, sorry for the name) with a project named 'atmosphere-spring'. It is a chat application, it works with tomcat7:run and when deployed as a war on Tomcat 7, but not when deployed as a war on Tomcat 8.

**Comment by jfarcand** [comment] 2015-09-16 22:17
@4th-line Thanks! I will look at it ASAP.

**Comment by 4th-line** [comment] 2015-09-16 23:12
I don't know if it helps, but if the servlet mapping is /* instead of / (see WebAppInitializer), opening a ws connection will results in calling Spring with an invalid path : ws://:0/atmosphere-spring/chat/connect
Once again, the problem only concerns deployment on tomcat 8.

Error, thrown by spring when atmosphere call Spring : expected hostname at index 5 : ws://:0/atmosphere-spring/chat/connect (URISyntaxException)

To test : change the servlet mapping in the WebAppInitializer, and change the line 8 in the index.html file

**Comment by jfarcand** [comment] 2015-09-16 23:46
@4th-line  What I suspect is this piece of code https://github.com/Atmosphere/atmosphere/blob/master/modules/cpr/src/main/java/org/atmosphere/container/JSR356AsyncSupport.java#L56-L71 . You can probably workaround the issue by setting the proper `ApplicationConfig.JSR356_PATH_MAPPING_LENGTH` init param. Will look tomorow!

**Comment by 4th-line** [comment] 2015-09-17 05:58
Hi, I am not sure to understand what this parameter is about, is it related to the servlet url mapping ?
The doc ("Value: MUST be set using System's properties: org.atmosphere.cpr.jsr356.pathMappingLength") is a bit cryptic to me.

I set it to 0 (I also tried 1) with a url mapping "/" or "/*".

Result : I hit the spring method but the javascript call (atmosphere.suscribe) receives an unexpected HTTP 200 response, so it switchs to lon polling (which is my fallback mode in the sample). Indeed, in the chrome console, the response status for the ws request is 200. I tried to explicitely add @ResponseStatus(HttpStatus.SWITCHING_PROTOCOLS) on the endpoint method that receives the connection (which in my opinion should not me done because the controller should not know about the protocol : websocket or http fallback, it's atmosphere responsability to return the appropriate status code).

With tomcat 7 : no problem, atmosphere.suscribe receives a HTTP 101.

**Comment by jfarcand** [comment] 2015-09-18 12:37
Root cause with jsr356:
```java
8:35:32 |  INFO | org.atmosphere.cpr.AtmosphereFramework:1747 | Installed WebSocketProtocol org.atmosphere.websocket.protocol.SimpleHttpProtocol
08:35:32 |  INFO | org.atmosphere.container.JSR356AsyncSupport:70 | JSR 356 Mapping path /{path}
08:35:32 |  INFO | org.atmosphere.cpr.AtmosphereFramework:1220 | Installing Default AtmosphereInterceptors
08:35:32 |  INFO | org.atmosphere.cpr.AtmosphereFramework:1239 | 	org.atmosphere.interceptor.CorsInterceptor : CORS Interceptor Support
```

**Comment by jfarcand** [comment] 2015-09-18 13:02
OK I discussed, adding
```java
		servlet.setInitParameter(org.atmosphere.cpr.ApplicationConfig.JSR356_MAPPING_PATH, "/sprint-atmosphere/");
```
fix the issue.

**Comment by jfarcand** [comment] 2015-09-18 14:56
Marking this issue as won't fix. It seems to be impossible to make it work with jsr356 + Spring as the ServletContext doesn't contains the '/spring-atmosphere' information Srping is using. So the only way yo make it work is to use the workaround.

**Comment by popkutty** [comment] 2015-09-18 15:20
@jfarcand Hi, where can I put this work around?  `servlet.setInitParameter(org.atmosphere.cpr.ApplicationConfig.JSR356_MAPPING_PATH, "/sprint-atmosphere/");` in web.xml is there anyway to put this param?

**Comment by jfarcand** [comment] 2015-09-18 15:22
@popkutty init-param

**Comment by 4th-line** [comment] 2015-09-18 18:42
Hi,

Thanks, setting the JSR356_MAPPING_PATH to something (the context path or /abcd or anything that starts with /) helps to hit the spring method. When I log the resource in the endpoint I get : 

AtmosphereResource{
	 uuid=b351f3db-3203-4f28-9a02-40479661db19,
	 transport=WEBSOCKET,
	 isInScope=true,
	 isResumed=false,
	 isCancelled=false,
	 isSuspended=false,
	 broadcasters=/,
	 isClosedByClient=false,
	 isClosedByApplication=false,
	 action=Action{timeout=-1, type=CREATED}}

But the browser receives a HTTP 200 in return, because the REST endpoint returns a 200 by default. I tried to add this code to the REST endpoint :

```javas
HttpHeaders headers= new HttpHeaders();
String inputKey = req.getHeader("Sec-WebSocket-Key")+ "258EAFA5-E914-47DA-95CA-C5AB0DC85B11";
byte[] sha = MessageDigest.getInstance("SHA-1").digest(inputKey.getBytes());
String websocketAccept = Base64.getEncoder().encodeToString(sha);

headers.add("Sec-WebSocket-Accept", websocketAccept );
headers.add("Upgrade", "websocket");
headers.add("Connection", "Upgrade");
return ResponseEntity.status(HttpStatus.SWITCHING_PROTOCOLS).headers(headers).build();
```
it helps to establish the connection but the call in the chrome console is "pending" and terminate after 20 seconds. Then the javascript client switchs to long-pooling.

Setting "org.atmosphere.cpr.asyncSupport" to org.atmosphere.container.JSR356AsyncSupport and ApplicationConfig.JSR356_PATH_MAPPING_LENGTH did not help.

**Comment by jfarcand** [comment] 2015-09-28 14:32
@4th-line Can you try latest `2.3.5-SNAPSHOT`. Thanks!

**Comment by jfarcand** [comment] 2015-10-02 19:42
@4th-line Ping?

**Comment by jfarcand** [comment] 2015-10-06 12:25
Maked as fixed.

**Closed by jfarcand** 2015-10-06 12:25 UTC
Labels: Documentation, Will not Fix, Workaround Available

**Comment by dwivedy** [comment] 2016-11-22 17:15
hey i m using tomcat 7.0.56 getting same error while using google chrome and in old browsers  its supports long polling transport. plz help

**Comment by dwivedy** [comment] 2016-11-22 17:23
hey i m using tomcat 7.0.56 getting same error while using google chrome and in old browsers its supports long polling transport. i m using atmosphere 2.4.7 with spring mvc 4. plz help

**Comment by dwivedy** [comment] 2016-11-23 11:34
Nov 22, 2016 8:45:29 AM org.springframework.web.servlet.DispatcherServlet noHandlerFound WARNING: No mapping found for HTTP request with URI [/chatbook/chat] in DispatcherServlet with name 'chatbook' [http-nio-8080-exec-6] WARN org.atmosphere.websocket.WebSocket - Unable to write 404 [http-nio-8080-exec-6] WARN org.atmosphere.websocket.protocol.SimpleHttpProtocol - Status code higher or equal than 400. Unable to deliver the websocket messages to installed component. Status 404 Message OK

**Comment by dwivedy** [comment] 2016-11-23 11:35
Nov 22, 2016 8:45:29 AM org.springframework.web.servlet.DispatcherServlet noHandlerFound WARNING: No mapping found for HTTP request with URI [/chatbook/chat] in DispatcherServlet with name 'chatbook' [http-nio-8080-exec-6] WARN org.atmosphere.websocket.WebSocket - Unable to write 404 [http-nio-8080-exec-6] WARN org.atmosphere.websocket.protocol.SimpleHttpProtocol - Status code higher or equal than 400. Unable to deliver the websocket messages to installed component. Status 404 Message OK

getting this error on using chrome n if use eclipse browser it shows long-polling tansport for atmosphereresource object and find conrrect mapping but not works with chrome and no mapping found.. what should i do .. plz help
