### ISSUE TITLE
Question onReconnect

### ISSUE THREAD

**Issue by supertick** [Atmosphere/atmosphere#2434] opened 2021-04-25 20:10 UTC
Hello,
Reading through the API Doc it says
```
onReconnect(AtmosphereRequest, AtmosphereResponse)
Invoked when the client reconnects to the server

```
In practice it really seems to be "when the client **_begins trying_** to reconnect to the server"
If the JS client does eventually "reconnect" there does not appear to be any callback for that event. (ie. onReconnected)

I would think the use case is pretty straight forward:
1. js client opens a connection - does some complicated logic
2. connection is lost
3. connection re-estabilshed, need to go through the complicated logic 

But regrettably, there doesn't seem to be a callback which tells the client that its "successfully" **reconnected**.

Is the only way to do this? Or, is the only way to start a timer of my own which continually checks the state and determines if the socket has successfully reconnected ?

Thanks for all your work !

Cheers,
Greg

**Comment by jfarcand** [comment] 2021-04-26 12:48
Duplicate of #2433

**Closed by jfarcand** 2021-04-26 12:48 UTC

**Comment by jfarcand** [comment] 2021-04-26 23:28
@supertick Use `onReopen` no? https://github.com/Atmosphere/atmosphere/wiki/Understanding-JavaScript-functions
