### ISSUE TITLE
Unable to configure jsr356 at that stage. ServerContainer is null

### ISSUE THREAD

**Issue by hapali** [Atmosphere/atmosphere#2090] opened 2015-11-22 14:14 UTC
Atmosphere Framework 2.4.0.1
tomcat 7 and 8

[localhost-startStop-1] WARN org.atmosphere.cpr.DefaultAsyncSupportResolver - Failed to create AsyncSupport class: class org.atmosphere.container.JSR356AsyncSupport, error: java.lang.reflect.InvocationTargetException
[localhost-startStop-1] ERROR org.atmosphere.cpr.DefaultAsyncSupportResolver - Real error: Unable to configure jsr356 at that stage. ServerContainer is null
java.lang.IllegalStateException: Unable to configure jsr356 at that stage. ServerContainer is null
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:51)
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:40)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.newCometSupport(DefaultAsyncSupportResolver.java:234)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolveWebSocket(DefaultAsyncSupportResolver.java:306)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolve(DefaultAsyncSupportResolver.java:292)
	at org.atmosphere.cpr.AtmosphereFramework.autoDetectContainer(AtmosphereFramework.java:2081)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:914)

```java
@Configuration
public class AtmosphereConfig {

	 @Bean
	    public AtmosphereFramework atmosphereFramework() throws ServletException, InstantiationException, IllegalAccessException {
	        AtmosphereFramework atmosphereFramework = new AtmosphereFramework(false, false);
	        atmosphereFramework.init(atmosphereSpringContext(), false);
	        List<AtmosphereInterceptor> interceptors = new ArrayList<>();
	        for (Class<? extends AtmosphereInterceptor> a : atmosphereFramework.defaultInterceptors()) {
	        	AtmosphereInterceptor interceptor = a.newInstance();
	        	interceptors.add(interceptor);
	        }
	        interceptors.addAll(interceptors());
	        atmosphereFramework.addAtmosphereHandler("/atmosphere", atmosphereHandler(), interceptors);
	        atmosphereFramework.sessionSupport(true);
	        return atmosphereFramework;
	    }

	    @Bean
	    public AtmosphereHandler atmosphereHandler() {
	        return new MyAtmosphereHandler();
	    }

	    private List<AtmosphereInterceptor> interceptors() {
	        List<AtmosphereInterceptor> atmosphereInterceptors = new ArrayList<>();
	        // atmosphereInterceptors.add(new TrackMessageSizeInterceptor());
	        return atmosphereInterceptors;
	    }

	    @Bean
	    public BroadcasterFactory broadcasterFactory() throws ServletException, InstantiationException, IllegalAccessException {
	        return atmosphereFramework().getAtmosphereConfig().getBroadcasterFactory();
	    }

	    @Bean
	    public AtmosphereSpringContext atmosphereSpringContext() {
	        AtmosphereSpringContext atmosphereSpringContext = new AtmosphereSpringContext();
	        Map<String, String> map = new HashMap<>();
	        map.put("org.atmosphere.cpr.broadcasterClass", org.atmosphere.cpr.DefaultBroadcaster.class.getName());
	        map.put(AtmosphereInterceptor.class.getName(), TrackMessageSizeInterceptor.class.getName());
	        //map.put(AnnotationProcessor.class.getName(), VoidAnnotationProcessor.class.getName());
	        map.put("org.atmosphere.cpr.broadcasterLifeCyclePolicy", ATMOSPHERE_RESOURCE_POLICY.IDLE_DESTROY.toString());
	        map.put("org.atmosphere.cpr.broadcaster.shareableThreadPool", "true");
	        map.put("org.atmosphere.cpr.scanClassPath", "false");
	        map.put("org.atmosphere.useNative", "false");
	        atmosphereSpringContext.setConfig(map);
	        return atmosphereSpringContext;
	    }
}
```

web.xml
```xml
<servlet>
        <description>AtmosphereServlet</description>
        <servlet-name>AtmosphereServlet</servlet-name>
        <servlet-class>org.atmosphere.spring.bean.AtmosphereSpringServlet</servlet-class>
        <async-supported>true</async-supported>
        <load-on-startup>0</load-on-startup>
    </servlet>
```

See wiki: https://github.com/Atmosphere/atmosphere/wiki/Configuring-Atmosphere-as-a-Spring-Bean

**Comment by elakito** [comment] 2015-12-08 23:23
I suppose this is the same issue that I have seen in other setup when JSR356 is detected (the relevant class is loadable) but the supplied servlet context to initialize atmosphere does not contain the valid JSR356 container.

I'm wondering if you could get around this issue in your setup so that the following line succeeds.
https://github.com/Atmosphere/atmosphere/blob/master/modules/cpr/src/main/java/org/atmosphere/container/JSR356AsyncSupport.java#L45

Otherwise, I just committed a change in 2.4.2-SNAPSHOT to suppress JSR356 detection for that case.
see https://github.com/Atmosphere/atmosphere/issues/2104
If you could try that option (setting the init parameter "org.atmosphere.suppressDetectingJSR356" to "true"), that would be appreciated.
This approach may change so please follow up on the above issue.
regards, aki

**Comment by elakito** [comment] 2015-12-09 19:46
we changed the name of the above property to "org.atmosphere.websocket.suppressSR356" and added constant WEBSOCKET_SUPPRESS_JSR356 in org.atmosphere.cpr.ApplicationConfig.

**Comment by hapali** [comment] 2015-12-14 09:33
"org.atmosphere.suppressDetectingJSR356" doesn't work. Do I need some snapshot version?

**Comment by seamusmac** [comment] 2015-12-14 09:47
I seen this last week after upgrading to 2.4.x.

The problem is with the AtmosphereSpringContext.getServletContext(), it doesn't return a usable servlet context, or some weird proxy.

I was able to fix the issue by extending the AtmosphereServlet, and the AtmosphereSpringContext.

```
public class AtmosphereContext extends AtmosphereSpringContext {
	private ServletContext servletContext;
	@Override
	public ServletContext getServletContext() {
		return servletContext;
	}
	public void setServletContext(ServletContext servletContext) {
		this.servletContext = servletContext;
	}
}

public class AtmosphereSpringServlet extends org.atmosphere.spring.bean.AtmosphereSpringServlet {

	@Autowired
	private AtmosphereFramework framework;

	@Autowired
	private AtmosphereContext atmosphereContext;

	@Autowired
	private DemoGwtHandler gwtHandler;

	@Override
	public void init(ServletConfig config) throws ServletException {
		super.init(config);

		// set the real servlet context
		atmosphereContext.setServletContext(config.getServletContext());

		framework.setBroadcasterCacheClassName(UUIDBroadcasterCache.class.getName());
		framework.init(atmosphereContext, false);
		framework.addAtmosphereHandler("/websockets/*", gwtHandler, interceptors());

		WebApplicationContextUtils.getRequiredWebApplicationContext(getServletContext()).getAutowireCapableBeanFactory().autowireBean(this);
	}

	private List<AtmosphereInterceptor> interceptors() {
		List<AtmosphereInterceptor> atmosphereInterceptors = new ArrayList<>();
		atmosphereInterceptors.add(new TrackMessageSizeInterceptor());
		atmosphereInterceptors.add(new ShiroInterceptor());
		return atmosphereInterceptors;
	}

}

**Comment by elakito** [comment] 2015-12-14 11:16
@seamusmac that sounds good. That means, we can just replace the current proxy-based context instantiation in AtmosphereSpringContext with the one that uses the actual servletContext if the context is set and uses the proxy-generated one only if the context is null). I suppose that will solve the problem. Could you create a PR?

@hapali the property is currently only in 2.4.2-SNAPSHOT.

**Comment by seamusmac** [comment] 2015-12-14 11:22
@elakito 
sure I will try possibly later in the week, I am travelling for the next few days.

It will need a slightly better solution though. I didn't really like moving the init method for atmosphere to the servlet, maybe if I change the bean load order in spring, I might be able to work it a bit better. WIll see.

**Comment by elakito** [comment] 2015-12-14 11:40
@seamusmac OK. Thanks. I thought, just changing AtmosphereSpringCotext would avoid this issue but that assumption seems to be wrong.

**Comment by seamusmac** [comment] 2016-01-08 11:50
@elakito I opened a PR that fixes the issue at https://github.com/Atmosphere/atmosphere-extensions/pull/217

I had to move the Atmosphereframework.init call into the Servlet.

Is it ok to add the handlers before we call the init method? I have tested and it seems to be work fine.

**Comment by seamusmac** [comment] 2016-01-14 14:40
@elakito @jfarcand Thanks for merging the PR. This issue can now be closed. It really should have been in the extensions project also.

**Comment by hapali** [comment] 2016-01-21 10:29
Is it possible to release a patch version for this fix?

**Comment by hapali** [comment] 2016-01-21 10:29
Is it possible to release a patch version for this fix?

**Comment by elakito** [comment] 2016-01-21 20:54
@hapali which patch are you talking about atmosphere or atmosphere-extensions?
atmosphere 2.4.2 is already out.

**Comment by seamusmac** [comment] 2016-01-21 21:14
@elakito @hapali atmosphere-extensions would need a 2.4.2 release to get this fix out.  I'm not sure if you want to do a new release with this fix yet. I'm in no major hurry and can wait a bit. 

@hapali do you want to confirm it works with the snapshot first.  It's at https://oss.sonatype.org/content/repositories/snapshots/org/atmosphere/atmosphere-spring/2.4.2-SNAPSHOT/

**Comment by elakito** [comment] 2016-01-22 11:02
@seamusmac @hapali there are two ways to avoid getting this issue, one is to use the suppressJSR356 option of atmosphere 2.4.2 which is already available and the other one is to use the updated atmosphere-extension, which is not yet available (needs a 2.4.2 release). So i asking @hapali which one was meant.

**Comment by seamusmac** [comment] 2016-01-22 11:16
@elakito I think the suppressJSR356 is not really needed. If you look at the very first post of this issue, you will see that the "ServerContainer was null in Spring", because it was not getting the real proper servletcontext.
That is the original problem, and your fix is merely a workaround, but the real fix is in the PR that I did

**Comment by elakito** [comment] 2016-01-22 11:31
@seamusmac i know your patch fixes the atmosphere-spring's JSR356 setup issue. And that is a clean solution for this specific case. In contrast, the suppress option can be used when your existing code instantiates atmosphere using its no-args constructor, which used to work for atmosphere 2.3.x but now fails with atmosphere 2.4.x.

**Comment by seamusmac** [comment] 2016-01-25 10:37
@elakito Anyways, thanks for the info. Its good to have the fix and the suppress option. Do you know when the next extensions release will be? 

I need to do a release of my product. And would like to have this fix in it, in next week or 2.
Thanks,
S

**Comment by jfarcand** [comment] 2016-01-25 14:29
@seamusmac Started. Should be available in a couple of hours: `2.4.2`

**Comment by elakito** [comment] 2016-01-25 15:11
@jfarcand thanks!

**Comment by elakito** [comment] 2016-01-25 15:28
updated atmosphere-samples' spring examples to use the new 2.4.2 and removed the previous workaround prop setting from those samples.

**Comment by seamusmac** [comment] 2016-01-25 15:35
@jfarcand Thanks a lot. 
If your ever in Ireland, I'll sort a nice pint of creamy black Guinness for you :)

I also updated the wiki for spring (https://github.com/Atmosphere/atmosphere/wiki/Configuring-Atmosphere-as-a-Spring-Bean)  to reflect the change this bug required.

**Comment by seamusmac** [comment] 2016-01-26 17:01
This issue can now be closed. I don't seem to have the privilege to do so.
@elakito @hapali Can you close please? Thanks.

**Closed** 2016-01-26 19:10 UTC

**Comment by elakito** [comment] 2016-01-26 19:21
closed this ticket (i didn't figure out how to change the component name of this issue to atmosphere-extension, so i created the below issue there so that it'll show up when you run a git query "is:closed label:2.4.2")
https://github.com/Atmosphere/atmosphere-extensions/issues/221

**Comment by hapali** [comment] 2016-02-08 10:18
The fix doesn't seem t work, see below. How can I reopen this issue?

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.atmosphere.cpr.AtmosphereFramework]: Factory method 'atmosphereFramework' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 46 more
Caused by: java.lang.NullPointerException
	at org.atmosphere.interceptor.OnDisconnectInterceptor.configure(OnDisconnectInterceptor.java:47)
	at org.atmosphere.cpr.AtmosphereFramework.addInterceptorToWrapper(AtmosphereFramework.java:2641)
	at org.atmosphere.cpr.AtmosphereFramework.createWrapperAndConfigureHandler(AtmosphereFramework.java:678)
	at org.atmosphere.cpr.AtmosphereFramework.addAtmosphereHandler(AtmosphereFramework.java:607)

**Comment by elakito** [comment] 2016-02-08 10:43
@hapali 
Your stack trace seems to show the secondary error and doesn't show why the initialization failed.
Maybe you should describe your setup in detail at the ML instead of reopening this ticket so that we know what is causing the issue and where (atmosphere, atmosphere-extension or elsewhere) it can be fixed. This ticket itself is getting too long (referring already two patches: the JSR356 disabling option in atmosphere and the atmosphere-spring fix in atmosphere-extension). Adding more stuff here won't really help in analyzing that issue. Therefore, it will be better to have a new thread and you can refer to this ticket from there.
regards, aki

**Comment by hapali** [comment] 2016-02-08 10:56
@elakito 
The stack trace very is clear and shows the root cause. NullPointerException on some Interceptor. 

Caused by: java.lang.NullPointerException
at org.atmosphere.interceptor.OnDisconnectInterceptor.configure(OnDisconnectInterceptor.java:47)

I can't help that this issue is getting too long, I want to upgrade but spring integration doesn't work. Setup is exactly same as described on this page: https://github.com/Atmosphere/atmosphere/wiki/Configuring-Atmosphere-as-a-Spring-Bean

**Comment by elakito** [comment] 2016-02-08 11:22
@hapali and i'm saying that is the secondary error that provides no insight to the root cause.
the initial error lead to the failed initialization of the framework which left this object null that lead to your stack trace.
if that wiki's setup is not working, please log it at atmosphere-extension where atmosphere-spring is hosted.

**Comment by seamusmac** [comment] 2016-02-08 11:52
@hapali I would also say create a new issue as elakito says on the extensions project. 

One thing to try:
Trying removing the 
atmosphereFramework.defaultInterceptors() for loop in setup.

The default interceptors are always installed unless explicitly disabled.

**Comment by hapali** [comment] 2016-02-08 13:50
@seamusmac your suggested workaround works. we have to update the spring wiki page.

**Comment by seamusmac** [comment] 2016-02-08 14:03
@elakito @hapali I have updated the wiki page to provide a configuration that doesn't cause the error you mention. (ie. I removed the for loop). Hopefully you will have no more problems now. :)

**Comment by FauxFaux** [comment] 2016-07-20 14:24
As this is the first Google result for this error right now, it also happens in Jetty if you haven't configured websockets. You need to call `WebSocketServerContainerInitializer.configureContext(context);` between `server.setHandler(..)` and `server.start()`.

(This took me about two hours to work out.)

**Comment by cliviu** [comment] 2018-03-02 09:38
@FauxFaux , can you please detail, I'm having the same problem but I'm not sure what I have to do to fix it

**Comment by FauxFaux** [comment] 2018-03-02 20:59
I no longer work at that company, and don't have access to the codebase. The description makes sense to me, however, do you not have those lines in your Jetty server setup?

**Comment by cliviu** [comment] 2018-03-02 22:04
I got it, thank you !
