### ISSUE TITLE
@postconstruct not working with atmosphere 2.4.0

### ISSUE THREAD

**Issue by scipio11** [Atmosphere/atmosphere#2084] opened 2015-11-06 11:56 UTC
Atmosphere 2.4.0 break  @postconstruct annotation (method is not called) under glassfish 4.1.1.  With wildfly 9.0 works fine.
glassfish 4.1.1 Primefaces 5.3 atmosphere 2.4.0

**Comment by seinecle** [comment] 2016-02-27 23:19
Hello! I try to get Atmosphere 2.4 to work on Glassfish 4.1 with Primefaces 5.3 but I get stuck with initialization errors.
Can I ask you what web.xml do you use? (the Atmosphere parts). Thanks!

**Comment by raffopiteco** [comment] 2016-12-05 11:40
Hi guys, I tried with Atmosphere 2.4.9 + Glassfish 4.1 + PrimeFaces 6.0.10 and I have had the same issue. However I noted that the issue occurs randomly because sometimes I simply had to restart Glassfish to resolve the issue. If I will able to find a workaround, I will inform you.

**Comment by zortx233** [comment] 2017-05-10 20:27
Confirmed this is still an issue with 2.4.9 + Payara 4.1.1.164 + PrimeFaces 6.1

**Comment by dparasam** [comment] 2017-09-22 23:45
I'm seeing this issue too - Glassfish 4.1 (with Mojarra 2.2.7), PrimeFaces 6.0.  Are there any work-arounds, other than restarting Glassfish?  Any ETA for the fix?

**Comment by jfarcand** [comment] 2018-06-18 21:53
Won't fix

**Closed by jfarcand** 2018-06-18 21:53 UTC
